### ISSUE TITLE
Mentions are light-gray

### ISSUE THREAD

**Issue by ALTracer** [Haron-Prime/4PDA-Dark-Style#1]
Упоминания серые на светло-сером фоне. Треды и Избранное нормальные, тёмные.
Firefox 57
![firefox_2017-11-23_16-29-23](https://user-images.githubusercontent.com/11005378/33175233-20ce9258-d06c-11e7-87c4-130d55456a6b.png)
![firefox_2017-11-23_16-32-30](https://user-images.githubusercontent.com/11005378/33175238-240cd1e6-d06c-11e7-8d78-cd6b74571aed.png)
Chrome 62
![chrome_2017-11-23_16-40-29](https://user-images.githubusercontent.com/11005378/33175671-82c4d9a8-d06d-11e7-9241-f1c7366bb23b.png)
![chrome_2017-11-23_16-43-34](https://user-images.githubusercontent.com/11005378/33175677-856c9ba0-d06d-11e7-8406-9485bbf95a32.png)

**Comment by Haron-Prime** [comment]
Я сегодня многое менял в данном стиле, в том числе пофиксил проблемы с фоном на некоторых страницах. На данный момент у меня фон везде отображается корректно.
![2017-11-23-211328_1920x1080_scrot](https://user-images.githubusercontent.com/6526819/33186579-35a154b4-d093-11e7-9e71-7ae8506b04ff.png)

Обновите стиль до актуальной версии - должно помочь.

**Comment by Haron-Prime** [comment]
Проблема устранена. Авторы оформления форума использовали !important для указания цвета фона этих блоков.
![2017-11-24-155404_1920x1080_scrot](https://user-images.githubusercontent.com/6526819/33213325-c4bf2864-d12f-11e7-9bf1-23e2d8aab973.png)
Я переопределил эти свойства другим способом, что решило проблему - фон сообщений остаётся тёмным как при первом открытии страницы, так и при её обновлении.
Спасибо за то, что указали на данную проблему!
